#just for fun, but still works
x = input("enter a string: ")
print("a = ", x.count("a"))
print("b = ", x.count("b"))
print("c = ", x.count("c"))
print("d = ", x.count("d"))
print("e = ", x.count("e"))
print("f = ", x.count("f"))
print("g = ", x.count("g"))
print("h = ", x.count("h"))
print("i = ", x.count("i"))
print("j = ", x.count("j"))
print("k = ", x.count("k"))
print("l = ", x.count("l"))
print("m = ", x.count("m"))
print("n = ", x.count("n"))
print("o = ", x.count("o"))
print("p = ", x.count("p"))
print("q = ", x.count("q"))
print("r = ", x.count("r"))
print("s = ", x.count("s"))
print("t = ", x.count("t"))
print("u = ", x.count("u"))
print("v = ", x.count("v"))
print("w = ", x.count("w"))
print("x = ", x.count("x"))
print("y = ", x.count("y"))
print("z = ", x.count("z"))


